In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../../Dataset/loan.csv')
df.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y


# Encoding

- Machine learning models work only with numbers
- Categorical features cannot be used directly
- Encoding helps preserve information in numeric form

## 1. Dummy Encoding

In [3]:
# when we have only limited catogrical data like gender, (yes, no), citizen then  that kind of data on we can use Ordinal Encoding

In [4]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [5]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Married'] = df['Married'].fillna(df['Married'].mode()[0])

### 1. using Pandas "get_dummis() method"

In [6]:
en_data = df[["Gender", "Married"]]
en_data

,Gender,Married
0,Male,No
1,Male,Yes
2,Male,Yes
3,Male,Yes
4,Male,No
...,...,...
609,Female,No
610,Male,Yes
611,Male,Yes
612,Male,Yes


In [7]:
dummies = pd.get_dummies(en_data)
dummies

,Gender_Female,Gender_Male,Married_No,Married_Yes
0,False,True,True,False
1,False,True,False,True
2,False,True,False,True
3,False,True,False,True
4,False,True,True,False
...,...,...,...,...
609,True,False,True,False
610,False,True,False,True
611,False,True,False,True
612,False,True,False,True


In [8]:
# Here we can show that show us data in boolean 
dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  614 non-null    bool 
 1   Gender_Male    614 non-null    bool 
 2   Married_No     614 non-null    bool 
 3   Married_Yes    614 non-null    bool 
dtypes: bool(4)
memory usage: 2.5 KB


In [9]:
# but we want to our data in Numerical form so we use scikit learn library so .... here is method...

## 2. One-Hot Encoding

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
ohe = OneHotEncoder()
data = ohe.fit_transform(en_data).toarray()

In [12]:
print(data)

[[0. 1. 1. 0.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]
 ...
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [13]:
pd.DataFrame(data, columns=dummies.columns)

,Gender_Female,Gender_Male,Married_No,Married_Yes
0,0.0,1.0,1.0,0.0
1,0.0,1.0,0.0,1.0
2,0.0,1.0,0.0,1.0
3,0.0,1.0,0.0,1.0
4,0.0,1.0,1.0,0.0
...,...,...,...,...
609,1.0,0.0,1.0,0.0
610,0.0,1.0,0.0,1.0
611,0.0,1.0,0.0,1.0
612,0.0,1.0,0.0,1.0


In [14]:
# OneHotEncoder return float value.
# what if we have 5 different data in our column then that OneHotEncoder generate 5 new columns
# that OneHotEncoder convert our dataset larger to larger
# what if we have one column like gender where one two different data in one column then if we get only one columns in data then we
#        know another value so "drop = 'first'" remove first one means now it is remove first column.

In [15]:
en_data.head()

,Gender,Married
0,Male,No
1,Male,Yes
2,Male,Yes
3,Male,Yes
4,Male,No


In [16]:
ohe = OneHotEncoder(drop='first')
data_drop = ohe.fit_transform(en_data).toarray()
data_drop

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       ...,
       [1., 1.],
       [1., 1.],
       [0., 0.]], shape=(614, 2))

In [17]:
# We can show here both of columns first column is delete
# Now we can get same information in two column if there is 0 then we just assume that have female or not merried

pd.DataFrame(data_drop, columns=['Gender_Male', 'Married_Yes'])

,Gender_Male,Married_Yes
0,1.0,0.0
1,1.0,1.0
2,1.0,1.0
3,1.0,1.0
4,1.0,0.0
...,...,...
609,0.0,0.0
610,1.0,1.0
611,1.0,1.0
612,1.0,1.0


## 3. Label Encoding

In [18]:
# when we need to give number in assending order in series then we are use labelEncoding
df = pd.DataFrame({"name":['Laksh', 'Cow', 'Laksh', 'Dog', 'Black']})
df

,name
0,Laksh
1,Cow
2,Laksh
3,Dog
4,Black


In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
le = LabelEncoder()
df['Asc'] = le.fit_transform(df['name'])

In [21]:
# now this new column Asc contains assending numbers / start from 0
# so using that label we can write all unique things identify with numbers
df

,name,Asc
0,Laksh,3
1,Cow,1
2,Laksh,3
3,Dog,2
4,Black,0


In [22]:
label_test = pd.read_csv('../../Dataset/loan.csv')
label_test.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y


In [23]:
label_test['Property_Area'].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [24]:
temp = le.fit(label_test['Property_Area'])
temp

LabelEncoder()

In [25]:
label_test['Property_Area'] = le.transform(label_test['Property_Area'])

In [26]:
# Now we can show all of them gives the numbers in assending order 
label_test['Property_Area']

0      2
1      0
2      2
3      2
4      2
      ..
609    0
610    0
611    2
612    2
613    1
Name: Property_Area, Length: 614, dtype: int64

In [27]:
# array(['Urban', 'Rural', 'Semiurban'], dtype=object) that convers in number in asc oders.
label_test['Property_Area'].unique()

array([2, 0, 1])

## 4. Ordinal Encoding

In [28]:
# there are two way to do that:
#    1. Cyclic Line
#    2. Map function

### i. Cyclic Line

In [29]:
# first we just make simple dataset for better understanding then we just apply on real or large dataset

df = pd.DataFrame({"Size":['s', 'm','l', 'xl', 's', 'm', 'l', 's', 's', 'l', 'xl', 'm']})
df.head(3)

,Size
0,s
1,m
2,l


In [30]:
ord_data = [['s', 'm', 'l', 'xl']]

In [31]:
from sklearn.preprocessing import OrdinalEncoder

In [32]:
oe = OrdinalEncoder(categories = ord_data)
oe.fit(df[["Size"]])

,categories,"[['s', 'm', ...]]"
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,unknown_value,None
,encoded_missing_value,nan
,min_frequency,None
,max_categories,None


In [33]:
df["size_oe"] = oe.transform(df[['Size']])

In [34]:
df.head()

,Size,size_oe
0,s,0.0
1,m,1.0
2,l,2.0
3,xl,3.0
4,s,0.0


### ii. Using Map 

In [35]:
ord_data1 = {"s": 0, "m":1, "l":2, "xl":6}
df['size_map'] = df['Size'].map(ord_data1)
df

,Size,size_oe,size_map
0,s,0.0,0
1,m,1.0,1
2,l,2.0,2
3,xl,3.0,6
4,s,0.0,0
5,m,1.0,1
6,l,2.0,2
7,s,0.0,0
8,s,0.0,0
9,l,2.0,2


In [36]:
# now we do Ordinal encoding with large dataset
label_test = pd.read_csv('../../Dataset/loan.csv')
label_test.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y


### iii. using order list

In [37]:
en_data_ord = [['Urban', 'Rural', 'Semiurban']]

In [38]:
from sklearn.preprocessing import OrdinalEncoder

In [39]:
oen = OrdinalEncoder(categories=en_data_ord)

In [40]:
label_test['Property_Area'] = oen.fit_transform(label_test[['Property_Area']])

In [41]:
label_test['Property_Area']

0      0.0
1      1.0
2      0.0
3      0.0
4      0.0
      ... 
609    1.0
610    1.0
611    0.0
612    0.0
613    2.0
Name: Property_Area, Length: 614, dtype: float64